/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import LopDoiTuong.ExcelHelper;
import LopDoiTuong.KetNoiQLBH;
import LopDoiTuong.KhachHang;
import LopDoiTuong.WordHelper;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hantr
 */
public class KhachHangF extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangF
     */
    KetNoiQLBH ketNoiQLlBH = null;
    Connection connection = null;
    ArrayList<KhachHang> listKhachHang = new ArrayList<>(); 

    public KhachHangF() throws ClassNotFoundException, SQLException {
        ketNoiQLlBH = new KetNoiQLBH();
        connection = ketNoiQLlBH.getJDBCConnect();
        initComponents();
        loadData();
        this.setLocationRelativeTo(null);
        listKhachHang = KhachHang.getlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ma = new javax.swing.JRadioButton();
        ten = new javax.swing.JRadioButton();
        dienthoai = new javax.swing.JRadioButton();
        socm = new javax.swing.JRadioButton();
        diachii = new javax.swing.JRadioButton();
        gioitinhhhh = new javax.swing.JRadioButton();
        emaillllll = new javax.swing.JRadioButton();
        timkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        makhachhang = new javax.swing.JTextField();
        tenkhachhang = new javax.swing.JTextField();
        sodienthoai = new javax.swing.JTextField();
        diachi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sochungminh = new javax.swing.JTextField();
        ngaysinh = new com.toedter.calendar.JDateChooser();
        gioitinh = new javax.swing.JComboBox();
        email = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangkhachhang = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tìm kiếm: ");

        buttonGroup1.add(ma);
        ma.setText("Mã khách hàng");

        buttonGroup1.add(ten);
        ten.setText("Tên khách hàng");

        buttonGroup1.add(dienthoai);
        dienthoai.setText("Số điện thoại");

        buttonGroup1.add(socm);
        socm.setText("Số chứng minh ND");

        buttonGroup1.add(diachii);
        diachii.setText("Địa chỉ");

        buttonGroup1.add(gioitinhhhh);
        gioitinhhhh.setText("Giới tính");

        buttonGroup1.add(emaillllll);
        emaillllll.setText("Email");

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xuất file");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập thông tin ");

        jLabel3.setText("Mã khách hàng: ");

        jLabel4.setText("Tên khách hàng: ");

        jLabel5.setText("Số điện thoại: ");

        jLabel6.setText("Địa chỉ: ");

        jLabel7.setText("Số chứng minh: ");

        jLabel8.setText("Ngày sinh :");

        jLabel9.setText("Giới tính :");

        jLabel10.setText("Email: ");

        gioitinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        jButton4.setText("Thêm ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Sửa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Xóa ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Thống kê");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        bangkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(bangkhachhang);

        jButton9.setText("Quay lại");

        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(283, 283, 283)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ma)
                                                    .addComponent(diachii)
                                                    .addComponent(dienthoai))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ten)
                                                    .addComponent(socm)
                                                    .addComponent(gioitinhhhh)))
                                            .addComponent(emaillllll)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addComponent(jButton1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(56, 56, 56)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(126, 126, 126)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(298, 298, 298)
                                        .addComponent(jButton4)
                                        .addGap(40, 40, 40)
                                        .addComponent(jButton5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(makhachhang)
                                        .addComponent(tenkhachhang)
                                        .addComponent(sodienthoai)
                                        .addComponent(diachi)
                                        .addComponent(sochungminh)
                                        .addComponent(ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(gioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(email))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(jButton7)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton8)))))
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ma)
                    .addComponent(ten)
                    .addComponent(jLabel3)
                    .addComponent(makhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dienthoai)
                    .addComponent(socm)
                    .addComponent(jLabel4)
                    .addComponent(tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diachii)
                    .addComponent(gioitinhhhh)
                    .addComponent(jLabel5)
                    .addComponent(sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillllll)
                    .addComponent(jLabel6)
                    .addComponent(diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(sochungminh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton8)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        makhachhang.setText("");
        tenkhachhang.setText("");
        sodienthoai.setText("");
        diachi.setText("");
        sochungminh.setText("");
        ngaysinh.setDate(null);
        email.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (ma.isSelected()) {
            timKiemTheoMa();
        } else if (ten.isSelected()) {
            timKiemTheoTen();
        } else if (dienthoai.isSelected()) {
            timKiemTheoSoDienThoai();
        } else if (diachii.isSelected()) {
            timKiemTheoDiaChi();
        } else if (socm.isSelected()) {
            timKiemTheoSoChungMinh();
        } else if (gioitinhhhh.isSelected()) {
            timKiemTheoGioiTinh();
        } else if (emaillllll.isSelected()) {
            timKiemTheoEmail();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            themKhachHang();
        } catch (SQLException ex) {
            Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();

        JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            suaKhachHang();
        } catch (SQLException ex) {
            Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
        JOptionPane.showMessageDialog(this, "Sửa khách hàng thành công!");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       int chose = JOptionPane.showConfirmDialog(null, "Xác nhận", "Thêm", 0);
        if (chose == 0) {
            try {
                xoaKhachHang();
            } catch (SQLException ex) {
                Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadData();
            JOptionPane.showMessageDialog(this, "Xóa khách hàng thành công!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new ThongKeKhachHangF().setVisible(true );
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            String type = file.getName().substring(file.getName().lastIndexOf(".") + 1);

            if (type.equals("xls") || type.equals("xlsx")) {
                try {
                    ArrayList<KhachHang> list = ExcelHelper.readKhachHang(file);
                    int re = -1;
                    for (KhachHang o : list) {
                        re = KhachHang.add(o);
                        if (re != 1) {
                            break;
                        }
                    }
                    if (re == 1) {
                        loadData();
                        JOptionPane.showMessageDialog(null, "Thêm thành công");
                    } else {
                        JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        if (jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();

            try {
                WordHelper.writeKhachHang(file, listKhachHang, "THÔNG TIN KHÁCH HÀNG");
                JOptionPane.showMessageDialog(null, "Xuất file thành công");

            } catch (IOException ex) {
                Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Xuất file thất bại!");
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KhachHangF().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(KhachHangF.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangkhachhang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField diachi;
    private javax.swing.JRadioButton diachii;
    private javax.swing.JRadioButton dienthoai;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton emaillllll;
    private javax.swing.JComboBox gioitinh;
    private javax.swing.JRadioButton gioitinhhhh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton ma;
    private javax.swing.JTextField makhachhang;
    private com.toedter.calendar.JDateChooser ngaysinh;
    private javax.swing.JTextField sochungminh;
    private javax.swing.JRadioButton socm;
    private javax.swing.JTextField sodienthoai;
    private javax.swing.JRadioButton ten;
    private javax.swing.JTextField tenkhachhang;
    private javax.swing.JTextField timkiem;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        bangkhachhang.removeAll();
        String sql = "select * from khachhang ; ";
        String[] columns = {"Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Số chứng minh", "Ngày sinh", "Giới tính", "Email"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("maKhachHang"));
                vector.add(resultSet.getString("tenKhachHang"));
                vector.add(resultSet.getString("sdtKhachHang"));
                vector.add(resultSet.getString("diachi"));
                vector.add(resultSet.getString("soCMT"));
                vector.add(resultSet.getDate("ngaySinh"));
                vector.add(resultSet.getString("gioiTinh"));
                vector.add(resultSet.getString("emailKhachHang"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangkhachhang.setModel(model);
        bangkhachhang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (bangkhachhang.getSelectedRow() >= 0) {
                    makhachhang.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 0).toString());
                    tenkhachhang.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 1).toString());
                    sodienthoai.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 2).toString());
                    diachi.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 3).toString());
                    sochungminh.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 4).toString());
                    ngaysinh.setDate((Date) bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 5));
                    gioitinh.setSelectedItem(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 6).toString());
                    email.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 7).toString());

                }
            }
        });
    }
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    private void timKiemTheoMa() {
        int input = Integer.parseInt(timkiem.getText());
        String sql = "select * from khachhang where maKhachHang ='" + input + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void thucThiSqlTimKiem(String sql) {
        bangkhachhang.removeAll();
        String[] columns = {"Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Số chứng minh", "Ngày sinh", "Giới tính", "Email"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        Statement statement = null;
        ResultSet resultSet = null;
        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
//                JOptionPane.showMessageDialog(null, resultSet.getDouble("giaTien"));
                Vector vector = new Vector();
                vector.add(resultSet.getInt("maKhachHang"));
                vector.add(resultSet.getString("tenKhachHang"));
                vector.add(resultSet.getString("sdtKhachHang"));
                vector.add(resultSet.getString("diachi"));
                vector.add(resultSet.getString("soCMT"));
                vector.add(resultSet.getDate("ngaySinh"));
                vector.add(resultSet.getString("gioiTinh"));
                vector.add(resultSet.getString("emailKhachHang"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
        bangkhachhang.setModel(model);
        bangkhachhang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (bangkhachhang.getSelectedRow() >= 0) {
                    makhachhang.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 0).toString());
                    tenkhachhang.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 1).toString());
                    sodienthoai.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 2).toString());
                    diachi.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 3).toString());
                    sochungminh.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 4).toString());
                    ngaysinh.setDate((Date) bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 5));
                    gioitinh.setSelectedItem(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 6).toString());
                    email.setText(bangkhachhang.getValueAt(bangkhachhang.getSelectedRow(), 7).toString());

                }
            }
        });
    }

    private void timKiemTheoTen() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where tenKhachHang ='" + input + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoSoDienThoai() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where sdtKhachHang ='" + input + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoDiaChi() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where diachi ='" + input + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoSoChungMinh() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where soCMT ='" + input + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoGioiTinh() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where gioiTinh ='" + input + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void timKiemTheoEmail() {
        String input = timkiem.getText();
        String sql = "select * from khachhang where emailKhachHang ='" + input + "'; ";

        thucThiSqlTimKiem(sql);
    }

    private void themKhachHang() throws SQLException {

        int maKhachHang = Integer.parseInt(makhachhang.getText().toString());
        String tenKhachHang = tenkhachhang.getText();
        String sdtKhachHang = sodienthoai.getText();
        String diaChi = diachi.getText();
        String soCMT = sochungminh.getText();
        String ngaySinh = dateFormat.format(ngaysinh.getDate());
        String gioiTinh = gioitinh.getSelectedItem().toString();
        String emailKhachHang = email.getText();
        String sql = "insert into khachhang (maKhachHang, tenKhachHang, sdtKhachHang , diachi, soCMT, ngaySinh,gioiTinh, emailKhachHang ) values ('" + maKhachHang + "','" + tenKhachHang + "', '" + sdtKhachHang + "', '" + diaChi + "', '" + soCMT + "', '" + ngaySinh + "', '" + gioiTinh + "', '" + emailKhachHang + "');";
        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql);

    }

    private void suaKhachHang() throws SQLException {
        int maKhachHang = Integer.parseInt(makhachhang.getText().toString());
        String tenKhachHang = tenkhachhang.getText();
        String sdtKhachHang = sodienthoai.getText();
        String diaChi = diachi.getText();
        String soCMT = sochungminh.getText();
        String ngaySinh = dateFormat.format(ngaysinh.getDate());
        String gioiTinh = gioitinh.getSelectedItem().toString();
        String emailKhachHang = email.getText();
        String sql = "update  khachhang set   tenKhachHang='" + tenKhachHang + "', sdtKhachHang='" + sdtKhachHang + "',diachi='" + diaChi + "',soCMT='" + soCMT + "',ngaySinh='" + ngaySinh + "',gioiTinh='" + gioiTinh + "',emailKhachHang='" + emailKhachHang + "'   where maKhachHang='" + maKhachHang + "';";
        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void xoaKhachHang() throws SQLException {
        
        int maKhachHang = Integer.parseInt(makhachhang.getText());
        
        String sql = "delete from khachhang where maKhachHang = " + maKhachHang;
        Statement statement = null;
        ResultSet resultSet = null;

        statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

}
