/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import LopDoiTuong.KetNoiQLBH;
import LopDoiTuong.ThongKeKhachHangType;
import LopDoiTuong.WordHelper;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hantr
 */
public class ThongKeKhachHangF extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeKhachHangF
     */
    KetNoiQLBH ketNoiQLlBH = null;
    Connection connection = null;
    ArrayList<ThongKeKhachHangType> listThongKe = new ArrayList<>();

    public ThongKeKhachHangF() {
        ketNoiQLlBH = new KetNoiQLBH();
        connection = ketNoiQLlBH.getJDBCConnect();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tenchon = new javax.swing.JRadioButton();
        gioitinhchon = new javax.swing.JRadioButton();
        diachichon = new javax.swing.JRadioButton();
        namsinhchon = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangthongke = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thống kê khách hàng");

        buttonGroup1.add(tenchon);
        tenchon.setText("Tên khách hàng ");
        tenchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenchonActionPerformed(evt);
            }
        });

        buttonGroup1.add(gioitinhchon);
        gioitinhchon.setText("Giới tính");
        gioitinhchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gioitinhchonActionPerformed(evt);
            }
        });

        buttonGroup1.add(diachichon);
        diachichon.setText("Địa chỉ");
        diachichon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diachichonActionPerformed(evt);
            }
        });

        buttonGroup1.add(namsinhchon);
        namsinhchon.setText("Năm sinh ");
        namsinhchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namsinhchonActionPerformed(evt);
            }
        });

        bangthongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bangthongke);

        jButton1.setText("Xuất file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tenchon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(gioitinhchon)
                .addGap(64, 64, 64)
                .addComponent(diachichon)
                .addGap(80, 80, 80)
                .addComponent(namsinhchon)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenchon)
                    .addComponent(gioitinhchon)
                    .addComponent(diachichon)
                    .addComponent(namsinhchon))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diachichonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diachichonActionPerformed
        // TODO add your handling code here:
        bangthongke.removeAll();
        String[] columns = {"Địa chỉ ", "Số lượng khách hàng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "SELECT diachi, count(maKhachHang)   FROM khachhang group by diachi order by count(maKhachHang) DESC ;";
        Statement statement = null;
        ResultSet resultSet = null;

        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("diachi"));
                vector.add(resultSet.getInt("count(maKhachHang)"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        bangthongke.setModel(model);
    }//GEN-LAST:event_diachichonActionPerformed

    private void gioitinhchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gioitinhchonActionPerformed
        // TODO add your handling code here:
        bangthongke.removeAll();
        String[] columns = {"Giới tính ", "Số lượng khách hàng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "SELECT gioiTinh, count(maKhachHang)   FROM khachhang group by gioiTinh order by count(maKhachHang) DESC ;";
        Statement statement = null;
        ResultSet resultSet = null;

        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("gioiTinh"));
                vector.add(resultSet.getInt("count(maKhachHang)"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        bangthongke.setModel(model);
    }//GEN-LAST:event_gioitinhchonActionPerformed

    private void tenchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenchonActionPerformed
        // TODO add your handling code here:
        bangthongke.removeAll();
        String[] columns = {"Tên khách hàng ", "Số lượng khách hàng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "SELECT tenKhachHang, count(maKhachHang)   FROM khachhang group by tenKhachHang order by count(maKhachHang) DESC ;";
        Statement statement = null;
        ResultSet resultSet = null;

        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("tenKhachHang"));
                vector.add(resultSet.getInt("count(maKhachHang)"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        bangthongke.setModel(model);
    }//GEN-LAST:event_tenchonActionPerformed

    private void namsinhchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namsinhchonActionPerformed
        // TODO add your handling code here:
        bangthongke.removeAll();
        String[] columns = {"Năm sinh ", "Số lượng khách hàng"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String sql = "SELECT year(ngaySinh), count(maKhachHang)   FROM khachhang group by year(ngaySinh) order by count(maKhachHang) DESC ;";
        Statement statement = null;
        ResultSet resultSet = null;

        try {
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("year(ngaySinh)"));
                vector.add(resultSet.getInt("count(maKhachHang)"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        bangthongke.setModel(model);
    }//GEN-LAST:event_namsinhchonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tenchon.isSelected()) {
            try {
                listThongKe = ThongKeKhachHangType.getlist("tenKhachHang");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            }
            JFileChooser jFileChooser = new JFileChooser();
            if (jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooser.getSelectedFile();

                try {
                    WordHelper.writeKhachHangTheoTen(file, listThongKe, "THỐNG KÊ KHÁCH HÀNG THEO TÊN");
                    JOptionPane.showMessageDialog(null, "Xuất file thành công");

                } catch (IOException ex) {
                    Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Xuất file thất bại!");
                }

            }
        }else if(gioitinhchon.isSelected()){
            try {
                listThongKe = ThongKeKhachHangType.getlist("gioiTinh");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            }
            JFileChooser jFileChooser = new JFileChooser();
            if (jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooser.getSelectedFile();

                try {
                    WordHelper.writeKhachHangTheoGioiTinh(file, listThongKe, "THỐNG KÊ KHÁCH HÀNG THEO GIỚI TÍNH");
                    JOptionPane.showMessageDialog(null, "Xuất file thành công");

                } catch (IOException ex) {
                    Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Xuất file thất bại!");
                }

            }
        }else if(diachichon.isSelected()){
            try {
                listThongKe = ThongKeKhachHangType.getlist("diachi");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            }
            JFileChooser jFileChooser = new JFileChooser();
            if (jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooser.getSelectedFile();

                try {
                    WordHelper.writeKhachHangTheoDiaChi(file, listThongKe, "THỐNG KÊ KHÁCH HÀNG THEO ĐỊA CHỈ");
                    JOptionPane.showMessageDialog(null, "Xuất file thành công");

                } catch (IOException ex) {
                    Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Xuất file thất bại!");
                }

            }
        }else if(namsinhchon.isSelected()){
            try {
                listThongKe = ThongKeKhachHangType.getlist("year(ngaySinh)");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
            }
            JFileChooser jFileChooser = new JFileChooser();
            if (jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooser.getSelectedFile();

                try {
                    WordHelper.writeKhachHangTheoNamSinh(file, listThongKe, "THỐNG KÊ KHÁCH HÀNG THEO NĂM SINH");
                    JOptionPane.showMessageDialog(null, "Xuất file thành công");

                } catch (IOException ex) {
                    Logger.getLogger(ThongKeKhachHangF.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Xuất file thất bại!");
                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeKhachHangF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeKhachHangF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangthongke;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton diachichon;
    private javax.swing.JRadioButton gioitinhchon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton namsinhchon;
    private javax.swing.JRadioButton tenchon;
    // End of variables declaration//GEN-END:variables
}
